services:
  store-storage-mongo:
    container_name: store-storage-mongo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8801:8801
    volumes:
      - ./config.json:/srv/config.json
