name: Deploy to EKS by call
# https://docs.github.com/en/actions/using-workflows/reusing-workflows
# see https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow
on:
  #push:
  #  branches:
  #    - stage
  workflow_dispatch:
    inputs:
      config-path:
        description: environment file name (i.e. .env.stage_auth)
      dir-to-upload:
        description: which dir put into container
        default: ./
jobs:
  build-and-deploy:
    #strategy:
    #  matrix: [dev,dev2,stage,prod]
    uses: Limpid-LLC/aws-deploy/.github/workflows/deploy-to-eks-shared.yml@main
      #with:
      #config-path: .env.master
    #dir-to-upload: ./nginx/
    #dir-to-upload: ./
    #target: ${{ matrix.target }}
    secrets: inherit
